name: ProgKor Java CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Configure Git for GitHub Packages
        run: |
          git config --global url."https://${{ secrets.GH_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Build and publish with Maven
        run: |
          cd MovieCatalog
          version="0.0.1-${{ github.run_number }}"
          echo "ARTIFACT_VERSION=$version" >> $GITHUB_ENV
          mvn versions:set -DnewVersion=$version
          mvn -B deploy --file pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}