name: ProgKor Java CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build and publish with Maven
        run: |
          cd MovieCatalog 
          version="${{github.run_number}}"
          echo "ARTIFACT_VERSION=$version" >> $GITHUB_ENV
          mvn -B deploy --file pom.xml
          cp "target/MovieCatalog-0.0.1-SNAPSHOT.jar" "target/MovieCatalog.jar"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}