name: ProgKor Java CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build and publish with Maven
        run: |
          # Versioning setup
          version_prefix=`mvn help:evaluate -Dexpression=project.version --quiet -DforceStdout --file MovieCatalog/pom.xml | awk -F. '{print $1"."$2}'`
          version="$version_prefix.${{github.run_number}}"
          echo "Setting artifact version to $version"
          # Push version to env
          echo "ARTIFACT_VERSION=$version" >> $GITHUB_ENV
          # Overwrite local artifact version
          mvn -B versions:set -DnewVersion="$version" --file MovieCatalog/pom.xml
          mvn -B deploy --file MovieCatalog/pom.xml
          cp "MovieCatalog/target/MovieCatalog-${version}.jar" "MovieCatalog/target/MovieCatalog.jar"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
