name: ProgKor Java CI

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and publish with Maven
        run: |
          cd MovieCatalog
          version="0.0.1-${{ github.run_number }}"
          echo "ARTIFACT_VERSION=$version" >> $GITHUB_ENV
          mvn versions:set -DnewVersion=$version
          mvn -B deploy --file pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
    - name: Build and push Docker image
      run: |
        docker build ./spring-core -t ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/spring-core:${{ env.ARTIFACT_VERSION }}
        docker push ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/spring-core:${{ env.ARTIFACT_VERSION }}